name: Publish Progress Report

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  update_progress:
    name: Update Progress
    if: github.repository == 'fmil95/soul-re'
    container: ghcr.io/fmil95/soul-re:latest
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        game_id: [ SLUS-00708 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHP }}
          submodules: recursive
          lfs: true

      - name: Copy Binary
        run: cp -r /game/* .

      - name: Setup
        run: make setup

      - name: Create Progress Report
        run: make report

      - name: Publish Progress Report
        uses: actions/upload-artifact@v4
        with:
            name: ${{ matrix.game_id }}_report
            path: ./build/progress.json
